# Tomcat
server:
  port: 8088

# Spring
spring:
  application:
    # 应用名称
    name: act-modules-zero
  main:
    allow-circular-references: true
  profiles:
    # 环境配置
    active: dev
  datasource:
    url: "jdbc:mysql://www.autoct.top:33306/java_act?characterEncoding=utf-8"
    username: "root"
    password: "qwe123QWE"

# mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#knife4j:
#  enable: true
#  openapi:
#    title: Zero 模块接口文档
#    description: "用户权限管理"
#    email: 1228115857@qq.com
#    concat: phil
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - com.knife4j.demo.new3